---
- name: "install asdf"
  become: yes
  become_user: deployer
  become_method: sudo
  git: repo="https://github.com/HashNuke/asdf.git" dest="~/.asdf" update=yes
  remote_user: "{{deployer}}"


- name: "source asdf in bashrc"
  become: yes
  become_user: deployer
  become_method: sudo
  lineinfile: dest="~/.bash_profile" create=yes line="source ~/.asdf/asdf.sh"
  remote_user: "{{deployer}}"


- name: "add asdf plugins"
  become: yes
  become_user: deployer
  become_method: sudo
  ignore_errors: yes
  command: "bash -lc 'asdf plugin-add {{item}} https://github.com/HashNuke/asdf-{{item}}.git'"
  with_items:
    - nodejs
    - erlang
    - elixir
  remote_user: "{{deployer}}"
